spring:
  datasource:
    url: jdbc:mysql://192.168.100.89:3306/gaza?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    database: mysql
    database-platform: MySQL8InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: secretcode
