spring:
  datasource:
    url: jdbc:mysql://i8c207.p.ssafy.io:3306/gaza?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  main:
    allow-bean-definition-overriding: true
  jwt:
    secret: "gazagazagazagazagazagazagaza"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  pattern:
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  file:
    name: ./log/logs.log
  level:
    root: info
    com.idel.gaza: Debug
<<<<<<< HEAD
redis:
  host: localhost
  port: 6379
=======

>>>>>>> d43fab826150e09aec0054cff0fc8754dc2b92cb
