spring:
  datasource:
    url: jdbc:mysql://i8c207.p.ssafy.io:3306/gaza?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  main:
    allow-bean-definition-overriding: true
  jwt:
    secret: "gazagazagazagazagazagazagaza"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      location: D:/SSAFY/upload-workspace
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  pattern:
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  file:
    name: ./log/logs.log
  level:
    root: info
    com.idle.gaza: Debug
redis:
  host: i8c207.p.ssafy.io
  port: 6379

